// frontend/react/src/pages/albums/AlbumsPage.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { AlbumCard } from '@/components/album/AlbumCard';
import { LoadingSpinner } from '@/components/common/LoadingSpinner';
import { EmptyState } from '@/components/common/EmptyState';
import { Pagination } from '@/components/common/Pagination';
import { albumService } from '@/api/services/albumService';
import { artistService } from '@/api/services/artistService';
import { genreService } from '@/api/services/genreService';
import { type Album } from '@/types/album';
import { type Artist } from '@/types/artist';
import { type Genre } from '@/types/genre';

const PAGE_SIZE = 12;

export const AlbumsPage: React.FC = () => {
  const [albums, setAlbums] = useState<Album[]>([]);
  const [artists, setArtists] = useState<Artist[]>([]);
  const [genres, setGenres] = useState<Genre[]>([]);
  const [selectedGenreIds, setSelectedGenreIds] = useState<number[]>([]);
  const [selectedArtistIds, setSelectedArtistIds] = useState<number[]>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(0);
  const [loading, setLoading] = useState(true);
  const [initialLoading, setInitialLoading] = useState(true);

  const hasSelectedFilters = selectedGenreIds.length > 0 || selectedArtistIds.length > 0;

  useEffect(() => {
    const loadInitialData = async () => {
      try {
        const [artistsData, genresData] = await Promise.all([
          artistService.getAll(),
          genreService.getAll(),
        ]);
        setArtists(artistsData);
        setGenres(genresData);
      } catch (error) {
        console.error('Error loading initial data:', error);
      } finally {
        setInitialLoading(false);
      }
    };

    loadInitialData();
  }, []);

  const loadAlbums = useCallback(async () => {
    setLoading(true);
    try {
      const filterRequest = {
        page: currentPage,
        size: PAGE_SIZE,
        ...(selectedGenreIds.length > 0 && { genreIds: selectedGenreIds }),
        ...(selectedArtistIds.length > 0 && { artistIds: selectedArtistIds }),
      };

      const response = await albumService.filterAlbums(filterRequest);
      setAlbums(response.content || []);
      setTotalPages(response.totalPages);
    } catch (error) {
      console.error('Error loading albums:', error);
      setAlbums([]);
    } finally {
      setLoading(false);
    }
  }, [currentPage, selectedGenreIds, selectedArtistIds]);

  useEffect(() => {
    if (!initialLoading) {
      loadAlbums();
    }
  }, [loadAlbums, initialLoading]);

  const handleGenreToggle = (genreId: number) => {
    setSelectedGenreIds(prev =>
      prev.includes(genreId)
        ? prev.filter(id => id !== genreId)
        : [...prev, genreId]
    );
    setCurrentPage(1);
  };

  const handleArtistToggle = (artistId: number) => {
    setSelectedArtistIds(prev =>
      prev.includes(artistId)
        ? prev.filter(id => id !== artistId)
        : [...prev, artistId]
    );
    setCurrentPage(1); 
  };

  const applyFilters = () => {
    loadAlbums();
  };

  const clearFilters = () => {
    setSelectedGenreIds([]);
    setSelectedArtistIds([]);
    setCurrentPage(1);
  };

  const isGenreSelected = (genreId: number) => selectedGenreIds.includes(genreId);
  const isArtistSelected = (artistId: number) => selectedArtistIds.includes(artistId);

  const renderContent = () => {
    if (loading) {
      return <LoadingSpinner />;
    }
    
    if (albums.length === 0) {
      return (
        <EmptyState
          icon="bi-music-note-beamed"
          message="Альбомы не найдены"
        />
      );
    }
    
    return (
      <>
        <div className="row g-4">
          {albums.map(album => (
            <div key={album.id} className="col-12 col-sm-6 col-md-4 col-lg-3">
              <AlbumCard album={album} />
            </div>
          ))}
        </div>

        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={setCurrentPage}
        />
      </>
    );
  };

  if (initialLoading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="container py-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h1 className="h3 mb-0">Альбомы</h1>
        {hasSelectedFilters && (
          <button
            className="btn btn-outline-primary"
            onClick={clearFilters}
          >
            <i className="bi bi-x-circle me-2"></i>
            Сбросить фильтры
          </button>
        )}
      </div>

      <div className="card shadow-sm mb-4">
        <div className="card-body">
          <div className="row g-3">
            <div className="col-md-5">
              <div className="fw-semibold mb-2">Жанры</div>
              <div className="d-flex flex-wrap gap-2">
                {genres.map(genre => (
                  <button
                    key={genre.id}
                    className={`btn btn-sm ${
                      isGenreSelected(genre.id)
                        ? 'btn-primary'
                        : 'btn-outline-secondary'
                    }`}
                    onClick={() => handleGenreToggle(genre.id)}
                  >
                    {genre.name}
                  </button>
                ))}
              </div>
            </div>

            <div className="col-md-5">
              <div className="fw-semibold mb-2">Исполнители</div>
              <div className="d-flex flex-wrap gap-2">
                {artists.map(artist => (
                  <button
                    key={artist.id}
                    className={`btn btn-sm ${
                      isArtistSelected(artist.id)
                        ? 'btn-primary'
                        : 'btn-outline-secondary'
                    }`}
                    onClick={() => handleArtistToggle(artist.id)}
                  >
                    {artist.name}
                  </button>
                ))}
              </div>
            </div>

            <div className="col-md-2 d-flex align-items-end">
              <button
                className="btn btn-primary w-100"
                onClick={applyFilters}
              >
                <i className="bi bi-search me-2"></i>
                Найти
              </button>
            </div>
          </div>
        </div>
      </div>

      {renderContent()}
    </div>
  );
};

// frontend/angular/src/app/features/albums/albums-page.component.ts
import { Component, OnInit, OnDestroy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AlbumService } from '../../core/services/album.service';
import { ArtistService } from '../../core/services/artist.service';
import { GenreService } from '../../core/services/genre.service';
import { Album, PageResponse } from '../../core/models/album.model';
import { Artist } from '../../core/models/artist.model';
import { Genre } from '../../core/models/genre.model';
import { AlbumCardComponent } from '../../shared/components/album-card/album-card.component';
import { Subject, takeUntil, forkJoin } from 'rxjs';

@Component({
  selector: 'app-albums-page',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    AlbumCardComponent
  ],
  templateUrl: './albums-page.component.html',
})
export class AlbumsPageComponent implements OnInit, OnDestroy {
  albums = signal<Album[]>([]);
  artists = signal<Artist[]>([]);
  genres = signal<Genre[]>([]);

  selectedGenreIds = signal<number[]>([]);
  selectedArtistIds = signal<number[]>([]);

  readonly pageSize = 12;
  currentPage = signal<number>(1);
  totalElements = signal<number>(0);
  totalPages = signal<number>(0);

  hasSelectedFilters = computed(() => 
    this.selectedGenreIds().length > 0 || this.selectedArtistIds().length > 0
  );

  pagesArray = computed(() => 
    Array.from({ length: this.totalPages() }, (_, i) => i + 1)
  );

  private readonly destroy$ = new Subject<void>();

  constructor(
    private readonly albumService: AlbumService,
    private readonly artistService: ArtistService,
    private readonly genreService: GenreService
  ) {}

  ngOnInit(): void {
    forkJoin({
      artists: this.artistService.getAll(),
      genres: this.genreService.getAll()
    })
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: ({ artists, genres }) => {
          this.artists.set(artists);
          this.genres.set(genres);
          this.loadFilteredAlbums();
        },
        error: (error) => {
          console.error('Error loading initial data:', error);
        }
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private loadFilteredAlbums(): void {
    const filterRequest: any = {
      page: this.currentPage(),
      size: this.pageSize
    };

    const genreIds = this.selectedGenreIds();
    const artistIds = this.selectedArtistIds();

    if (genreIds.length > 0) {
      filterRequest.genreIds = genreIds;
    }

    if (artistIds.length > 0) {
      filterRequest.artistIds = artistIds;
    }

    this.albumService.filterAlbums(filterRequest)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response: PageResponse<Album>) => {
          this.albums.set(response.content || []);
          this.currentPage.set(response.page);
          this.totalElements.set(response.totalElements);
          this.totalPages.set(response.totalPages);
        },
        error: (error) => {
          console.error('Error loading albums:', error);
          this.albums.set([]);
        }
      });
  }

  applyFilters(): void {
    this.currentPage.set(1);
    this.loadFilteredAlbums();
  }

  onPageChange(page: number): void {
    if (page === this.currentPage()) {
      return;
    }
    
    if (page >= 1 && page <= this.totalPages()) {
      this.currentPage.set(page);
      this.loadFilteredAlbums();
    }
  }

  clearFilters(): void {
    this.selectedGenreIds.set([]);
    this.selectedArtistIds.set([]);
    this.applyFilters();
  }

  toggleGenre(genreId: number): void {
    this.selectedGenreIds.update(ids => {
      const index = ids.indexOf(genreId);
      if (index === -1) {
        return [...ids, genreId];
      } else {
        return ids.filter(id => id !== genreId);
      }
    });
  }

  toggleArtist(artistId: number): void {
    this.selectedArtistIds.update(ids => {
      const index = ids.indexOf(artistId);
      if (index === -1) {
        return [...ids, artistId];
      } else {
        return ids.filter(id => id !== artistId);
      }
    });
  }

  isGenreSelected(genreId: number): boolean {
    return this.selectedGenreIds().includes(genreId);
  }

  isArtistSelected(artistId: number): boolean {
    return this.selectedArtistIds().includes(artistId);
  }
}
<div class="container py-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0">Альбомы</h1>
    <button 
      *ngIf="hasSelectedFilters()"
      class="btn btn-outline-primary"
      (click)="clearFilters()">
      <i class="bi bi-x-circle me-2"></i>
      Сбросить фильтры
    </button>
  </div>

  <div class="card shadow-sm mb-4">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-5">
          <div class="fw-semibold mb-2">Жанры</div>
          <div class="d-flex flex-wrap gap-2">
            <button 
              *ngFor="let genre of genres()"
              class="btn btn-sm"
              [class.btn-primary]="isGenreSelected(genre.id)"
              [class.btn-outline-secondary]="!isGenreSelected(genre.id)"
              (click)="toggleGenre(genre.id)">
              {{ genre.name }}
            </button>
          </div>
        </div>

        <div class="col-md-5">
          <div class="fw-semibold mb-2">Исполнители</div>
          <div class="d-flex flex-wrap gap-2">
            <button 
              *ngFor="let artist of artists()"
              class="btn btn-sm"
              [class.btn-primary]="isArtistSelected(artist.id)"
              [class.btn-outline-secondary]="!isArtistSelected(artist.id)"
              (click)="toggleArtist(artist.id)">
              {{ artist.name }}
            </button>
          </div>
        </div>

        <div class="col-md-2 d-flex align-items-end">
          <button 
            class="btn btn-primary w-100"
            (click)="applyFilters()">
            <i class="bi bi-search me-2"></i>
            Найти
          </button>
        </div>
      </div>
    </div>
  </div>

  <div *ngIf="albums().length === 0" class="text-center py-5">
    <i class="bi bi-music-note-beamed" style="font-size: 3rem; color: #ccc;"></i>
    <p class="mt-3 text-muted">Альбомы не найдены</p>
  </div>

  <div *ngIf="albums().length > 0" class="row g-4">
    <div *ngFor="let album of albums()" class="col-12 col-sm-6 col-md-4 col-lg-3">
      <app-album-card [album]="album"></app-album-card>
    </div>
  </div>

  <nav *ngIf="totalPages() > 1" class="mt-4 d-flex justify-content-center" aria-label="Навигация по страницам">
    <ul class="pagination">
      <li class="page-item" [class.disabled]="currentPage() === 1">
        <a class="page-link" href="#" (click)="onPageChange(1); $event.preventDefault()">
          <i class="bi bi-chevron-double-left"></i>
        </a>
      </li>
      
      <li class="page-item" [class.disabled]="currentPage() === 1">
        <a class="page-link" href="#" (click)="onPageChange(currentPage() - 1); $event.preventDefault()">
          <i class="bi bi-chevron-left"></i>
        </a>
      </li>

      <li *ngFor="let page of pagesArray()" 
          class="page-item" 
          [class.active]="currentPage() === page">
        <a class="page-link" href="#" (click)="onPageChange(page); $event.preventDefault()">
          {{ page }}
        </a>
      </li>
      
      <li class="page-item" [class.disabled]="currentPage() === totalPages()">
        <a class="page-link" href="#" (click)="onPageChange(currentPage() + 1); $event.preventDefault()">
          <i class="bi bi-chevron-right"></i>
        </a>
      </li>
      
      <li class="page-item" [class.disabled]="currentPage() === totalPages()">
        <a class="page-link" href="#" (click)="onPageChange(totalPages()); $event.preventDefault()">
          <i class="bi bi-chevron-double-right"></i>
        </a>
      </li>
    </ul>
  </nav>
</div>
