// frontend/react/src/components/playlist/PlaylistCard.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { type Playlist, getPlaylistCoverUrl } from '@/types/playlist';
import './PlaylistCard.css';

interface PlaylistCardProps {
  playlist: Playlist;
}

export const PlaylistCard: React.FC<PlaylistCardProps> = ({ playlist }) => {
  return (
    <Link to={`/playlists/${playlist.id}`} className="text-decoration-none">
      <div className="card h-100 shadow-sm playlist-card">
        <img 
          src={getPlaylistCoverUrl(playlist)} 
          alt={playlist.name}
          className="card-img-top"
          style={{ aspectRatio: '1/1', objectFit: 'cover' }}
        />
        <div className="card-body">
          <h5 className="card-title text-truncate text-dark">{playlist.name}</h5>
          <p className="card-text small text-muted">
            <i className="bi bi-person-circle me-1"></i>
            {playlist.userName} · {playlist.tracks.length} треков
          </p>
        </div>
      </div>
    </Link>
  );
};

// frontend/angular/src/app/shared/components/playlist-card/playlist-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Playlist, getPlaylistCoverUrl } from '../../../core/models/playlist.model';

@Component({
  selector: 'app-playlist-card',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './playlist-card.component.html'
})
export class PlaylistCardComponent {
  @Input({ required: true }) playlist!: Playlist;

  protected readonly getPlaylistCoverUrl = getPlaylistCoverUrl;
}
<a [routerLink]="['/playlists', playlist.id]" class="text-decoration-none">
  <div class="card h-100 shadow-sm">
    <img 
      [src]="getPlaylistCoverUrl(playlist)" 
      [alt]="playlist.name"
      class="card-img-top"
      style="aspect-ratio: 1/1; object-fit: cover;">
    <div class="card-body">
      <h5 class="card-title text-truncate text-dark">{{ playlist.name }}</h5>
      <p class="card-text small text-muted">{{ playlist.tracks.length }} треков</p>
    </div>
  </div>
</a>
