// frontend/angular/src/app/shared/components/player/player.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { PlayerService } from '../../../core/services/player.service';

@Component({
  selector: 'app-player',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './player.component.html',
  styleUrls: ['./player.component.scss']
})
export class PlayerComponent {
  constructor(public playerService: PlayerService) {}

  togglePlay(): void {
    this.playerService.togglePlay();
  }

  playNext(): void {
    this.playerService.playNext();
  }

  playPrevious(): void {
    this.playerService.playPrevious();
  }

  onProgressClick(event: MouseEvent): void {
    const progressBar = event.currentTarget as HTMLElement;
    const rect = progressBar.getBoundingClientRect();
    const clickX = event.clientX - rect.left;
    const percentage = (clickX / rect.width) * 100;
    this.playerService.seekByPercentage(percentage);
  }

  formatTime(seconds: number): string {
    return this.playerService.formatTime(seconds);
  }

  onVolumeChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.playerService.setVolume(Number.parseFloat(input.value));
  }

  toggleMute(): void {
    this.playerService.toggleMute();
  }

  formatArtists(artists: { name: string }[]): string {
    return artists.map(a => a.name).join(', ');
  }

  getVolumeIcon(): string {
    const { isMuted, volume } = this.playerService;
    
    if (isMuted() || volume() === 0) {
      return 'bi-volume-mute-fill';
    }
    if (volume() > 0.5) {
      return 'bi-volume-up-fill';
    }
    return 'bi-volume-down-fill';
  }

  getVolumePercentage(): number {
    return Math.floor(this.playerService.volume() * 100);
  }
}
@if (playerService.currentTrack(); as track) {
  <div class="player-container">
    <div class="player-content">
      <div class="track-info">
        <div class="track-details">
          <div class="track-title">{{ track.title }}</div>
          <div class="track-artist">{{ formatArtists(track.artists) }}</div>
        </div>
      </div>

      <div class="player-controls">
        <div class="control-buttons">
          <button 
            class="btn btn-link text-white p-2" 
            [class.disabled]="!playerService.hasPrevious()"
            (click)="playPrevious()"
            [disabled]="!playerService.hasPrevious()">
            <i class="bi bi-skip-backward-fill fs-5"></i>
          </button>

          <button 
            class="btn btn-light rounded-circle p-0 play-button" 
            (click)="togglePlay()">
            <i class="bi" 
               [class.bi-play-fill]="!playerService.isPlaying()" 
               [class.bi-pause-fill]="playerService.isPlaying()">
            </i>
          </button>

          <button 
            class="btn btn-link text-white p-2" 
            [class.disabled]="!playerService.hasNext()"
            (click)="playNext()"
            [disabled]="!playerService.hasNext()">
            <i class="bi bi-skip-forward-fill fs-5"></i>
          </button>
        </div>

        <div class="progress-container">
          <span class="time-current">{{ formatTime(playerService.currentTime()) }}</span>
          <div class="progress-bar-wrapper" (click)="onProgressClick($event)">
            <div class="progress">
              <div 
                class="progress-bar bg-light" 
                [style.width.%]="playerService.currentProgress()">
              </div>
            </div>
          </div>
          <span class="time-total">{{ formatTime(playerService.duration()) }}</span>
        </div>
      </div>

      <div class="volume-control">
        <button class="btn btn-link text-white p-2" (click)="toggleMute()">
          <i class="bi" [class]="getVolumeIcon()"></i>
        </button>
        
        <div class="volume-slider-container">
          <input 
            type="range" 
            class="form-range volume-slider" 
            [value]="playerService.volume()"
            min="0" 
            max="1" 
            step="0.01"
            (input)="onVolumeChange($event)">
          <span class="volume-percentage">{{ getVolumePercentage() }}%</span>
        </div>
      </div>
    </div>
  </div>
}

// frontend/react/src/components/player/Player.tsx
import React, { useRef } from 'react';
import { usePlayer } from '@/contexts/PlayerContext';
import './Player.css';

export const Player: React.FC = () => {
  const player = usePlayer();
  const progressBarRef = useRef<HTMLDivElement>(null);

  if (!player.currentTrack) {
    return null;
  }

  const formatArtists = (artists: { name: string }[]): string => {
    return artists.map(a => a.name).join(', ');
  };

  const handleProgressClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (!progressBarRef.current) return;

    const rect = progressBarRef.current.getBoundingClientRect();
    const clickX = event.clientX - rect.left;
    const percentage = (clickX / rect.width) * 100;
    player.seekByPercentage(percentage);
  };

  const handleVolumeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const volume = Number.parseFloat(event.target.value);
    player.setVolume(volume);
  };

  const getVolumeIcon = (): string => {
    if (player.isMuted || player.volume === 0) {
      return 'bi-volume-mute-fill';
    }
    if (player.volume > 0.5) {
      return 'bi-volume-up-fill';
    }
    return 'bi-volume-down-fill';
  };

  const getVolumePercentage = (): number => {
    return Math.floor(player.volume * 100);
  };

  return (
    <div className="player-container">
      <div className="player-content">
        <div className="track-info">
          <div className="track-details">
            <div className="track-title">{player.currentTrack.title}</div>
            <div className="track-artist">{formatArtists(player.currentTrack.artists)}</div>
          </div>
        </div>

        <div className="player-controls">
          <div className="control-buttons">
            <button
              className={`btn btn-link text-white p-2 ${player.hasPrevious ? '' : 'disabled'}`}
              onClick={player.playPrevious}
              disabled={!player.hasPrevious}
            >
              <i className="bi bi-skip-backward-fill fs-5"></i>
            </button>

            <button
              className="btn btn-light rounded-circle p-0 play-button"
              onClick={player.togglePlay}
            >
              <i className={`bi ${player.isPlaying ? 'bi-pause-fill' : 'bi-play-fill'}`}></i>
            </button>

            <button
              className={`btn btn-link text-white p-2 ${player.hasNext ? '' : 'disabled'}`}
              onClick={player.playNext}
              disabled={!player.hasNext}
            >
              <i className="bi bi-skip-forward-fill fs-5"></i>
            </button>
          </div>

          <div className="progress-container">
            <span className="time-current">{player.formatTime(player.currentTime)}</span>
            <div className="progress-bar-wrapper" onClick={handleProgressClick} ref={progressBarRef}>
              <div className="progress">
                <div
                  className="progress-bar bg-light"
                  style={{ width: `${player.currentProgress}%` }}
                ></div>
              </div>
            </div>
            <span className="time-total">{player.formatTime(player.duration)}</span>
          </div>
        </div>

        <div className="volume-control">
          <button className="btn btn-link text-white p-2" onClick={player.toggleMute}>
            <i className={`bi ${getVolumeIcon()}`}></i>
          </button>

          <div className="volume-slider-container">
            <input
              type="range"
              className="form-range volume-slider"
              value={player.volume}
              min="0"
              max="1"
              step="0.01"
              onChange={handleVolumeChange}
            />
            <span className="volume-percentage">{getVolumePercentage()}%</span>
          </div>
        </div>
      </div>
    </div>
  );
};
