// frontend/angular/src/app/shared/components/album-card/album-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Album, getAlbumCoverUrl } from '../../../core/models/album.model';

@Component({
  selector: 'app-album-card',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './album-card.component.html',
  styleUrls: ['./album-card.component.scss']
})
export class AlbumCardComponent {
  @Input({ required: true }) album!: Album;

  protected readonly getAlbumCoverUrl = getAlbumCoverUrl;
}
<a [routerLink]="['/albums', album.id]" class="text-decoration-none">
  <div class="card h-100 shadow-sm album-card">
    <img 
      [src]="getAlbumCoverUrl(album)" 
      [alt]="album.title"
      class="card-img-top"
      style="aspect-ratio: 1/1; object-fit: cover;">
    <div class="card-body">
      <h5 class="card-title text-truncate text-dark">{{ album.title }}</h5>
    </div>
  </div>
</a>

// frontend/react/src/components/album/AlbumCard.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { type Album, getAlbumCoverUrl } from '@/types/album';
import './AlbumCard.css';

interface AlbumCardProps {
  album: Album;
}

export const AlbumCard: React.FC<AlbumCardProps> = ({ album }) => {
  return (
    <Link to={`/albums/${album.id}`} className="text-decoration-none">
      <div className="card h-100 shadow-sm album-card">
        <img 
          src={getAlbumCoverUrl(album)} 
          alt={album.title}
          className="card-img-top"
          style={{ aspectRatio: '1/1', objectFit: 'cover' }}
        />
        <div className="card-body">
          <h5 className="card-title text-truncate text-dark">{album.title}</h5>
        </div>
      </div>
    </Link>
  );
};
