// frontend/react/src/pages/playlists/PlaylistsPage.tsx
import React, { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useNotification } from '@/contexts/NotificationContext';
import { usePlayer } from '@/contexts/PlayerContext';
import { playlistService } from '@/api/services/playlistService';
import { PlaylistSidebar } from '@/components/playlist/PlaylistSidebar';
import { TrackPositionModal } from '@/components/playlist/TrackPositionModal';
import { LoadingSpinner } from '@/components/common/LoadingSpinner';
import { Link } from 'react-router-dom';
import { getPlaylistCoverUrl } from '@/types/playlist';
import type { Playlist } from '@/types/playlist';
import type { Track } from '@/types/track';
import './PlaylistsPage.css';

export const PlaylistsPage: React.FC = () => {
  const [playlists, setPlaylists] = useState<Playlist[]>([]);
  const [selectedPlaylist, setSelectedPlaylist] = useState<Playlist | null>(null);
  const [loading, setLoading] = useState(true);
  const [deleteConfirmId, setDeleteConfirmId] = useState<number | null>(null);
  const [showPositionModal, setShowPositionModal] = useState(false);
  const [selectedTrackForPosition, setSelectedTrackForPosition] = useState<Track | null>(null);

  const { user } = useAuth();
  const { success, error } = useNotification();
  const player = usePlayer();

  useEffect(() => {
    if (user) {
      loadPlaylists();
    }
  }, [user]);

  const loadPlaylists = async () => {
    if (!user) return;

    setLoading(true);
    try {
      const data = await playlistService.getUserPlaylists(user.id);
      setPlaylists(data);
      if (data.length > 0) {
        setSelectedPlaylist(data[0]);
      }
    } catch (err) {
      error('Ошибка при загрузке плейлистов');
    } finally {
      setLoading(false);
    }
  };

  const handleSelectPlaylist = (playlist: Playlist) => {
    setSelectedPlaylist(playlist);
  };

  const handlePlayTrack = (track: Track, tracks: Track[]) => {
    player.playTrack(track, tracks);
  };

  const handleRemoveTrack = async (playlistId: number, trackId: number) => {
    try {
      const updatedPlaylist = await playlistService.removeTrack(playlistId, trackId);
      success('Трек удален из плейлиста');
      
      setPlaylists(prev => 
        prev.map(p => p.id === playlistId ? updatedPlaylist : p)
      );
      
      if (selectedPlaylist?.id === playlistId) {
        setSelectedPlaylist(updatedPlaylist);
      }
    } catch (err) {
      error('Ошибка при удалении трека');
    }
  };

  const handleOpenPositionModal = (track: Track) => {
    setSelectedTrackForPosition(track);
    setShowPositionModal(true);
  };

  const handlePositionChanged = async (newPosition: number) => {
    if (!selectedPlaylist || !selectedTrackForPosition) return;

    try {
      const updatedPlaylist = await playlistService.updateTrackPosition(
        selectedPlaylist.id,
        selectedTrackForPosition.id,
        newPosition
      );
      
      success('Позиция трека изменена');
      
      setPlaylists(prev => 
        prev.map(p => p.id === selectedPlaylist.id ? updatedPlaylist : p)
      );
      
      setSelectedPlaylist(updatedPlaylist);
      setShowPositionModal(false);
      setSelectedTrackForPosition(null);
    } catch (err) {
      error('Ошибка при изменении позиции трека');
    }
  };

  const handleDeleteClick = (playlistId: number) => {
    setDeleteConfirmId(playlistId);
  };

  const handleCancelDelete = () => {
    setDeleteConfirmId(null);
  };

  const handleConfirmDelete = async (playlistId: number) => {
    try {
      await playlistService.delete(playlistId);
      success('Плейлист удален');
      
      const updatedPlaylists = playlists.filter(p => p.id !== playlistId);
      setPlaylists(updatedPlaylists);
      
      if (selectedPlaylist?.id === playlistId) {
        setSelectedPlaylist(updatedPlaylists[0] || null);
      }
      
      setDeleteConfirmId(null);
    } catch (err) {
      error('Ошибка при удалении плейлиста');
    }
  };

  const formatArtists = (artists: { name: string }[]): string => {
    return artists.map(a => a.name).join(', ');
  };

  const formatDuration = (seconds: number): string => {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="container-fluid py-4">
      <div className="row g-4">
        <div className="col-md-4 col-lg-3">
          <PlaylistSidebar
            playlists={playlists}
            selectedPlaylist={selectedPlaylist}
            onSelectPlaylist={handleSelectPlaylist}
            onDeleteClick={handleDeleteClick}
            deleteConfirmId={deleteConfirmId}
            onConfirmDelete={handleConfirmDelete}
            onCancelDelete={handleCancelDelete}
          />
        </div>

        <div className="col-md-8 col-lg-9">
          {selectedPlaylist ? (
            <div className="card shadow-sm border-0">
              <div className="card-header bg-white py-3 border-bottom">
                <div className="d-flex align-items-center gap-3">
                  <img 
                    src={getPlaylistCoverUrl(selectedPlaylist)}
                    alt="Обложка плейлиста" 
                    className="rounded shadow-sm"
                    style={{ width: '80px', height: '80px', objectFit: 'cover' }}
                  />
                  <div className="flex-grow-1">
                    <div className="d-flex align-items-center gap-2 mb-1">
                      <h1 className="h3 mb-0">{selectedPlaylist.name}</h1>
                      <span className={`badge ${selectedPlaylist.isPublic ? 'bg-success' : 'bg-secondary'}`}>
                        {selectedPlaylist.isPublic ? 'Публичный' : 'Приватный'}
                      </span>
                    </div>
                    <p className="text-muted mb-0">
                      <i className="bi bi-music-note-beamed me-1"></i>
                      {selectedPlaylist.tracks.length} треков
                    </p>
                  </div>
                  <div className="d-flex gap-2">
                    <Link 
                      to={`/playlists/${selectedPlaylist.id}/edit`} 
                      className="btn btn-outline-primary"
                    >
                      <i className="bi bi-pencil me-2"></i>
                      Редактировать
                    </Link>
                  </div>
                </div>
              </div>

              <div className="card-body p-0">
                <div className="list-group list-group-flush">
                  {selectedPlaylist.tracks.length === 0 ? (
                    <div className="text-center py-5">
                      <i className="bi bi-music-note-beamed" style={{ fontSize: '3rem', color: '#ccc' }}></i>
                      <p className="mt-3 text-muted">В плейлисте нет треков</p>
                      <Link to="/albums" className="btn btn-primary mt-2">
                        <i className="bi bi-plus-circle me-2"></i>
                        Добавить треки
                      </Link>
                    </div>
                  ) : (
                    selectedPlaylist.tracks.map((track, index) => (
                      <div key={track.id} className="list-group-item p-3">
                        <div className="row align-items-center g-3">
                          <div className="col-auto">
                            <span className="text-secondary fw-medium" style={{ width: '30px', display: 'inline-block' }}>
                              {index + 1}
                            </span>
                          </div>
                          
                          <div className="col">
                            <div className="d-flex flex-column">
                              <h3 className="h6 mb-1">{track.title}</h3>
                              <div className="small text-secondary">
                                {formatArtists(track.artists)} · {formatDuration(track.durationSeconds)}
                              </div>
                            </div>
                          </div>
                          
                          <div className="col-auto">
                            <div className="d-flex gap-2">
                              <button 
                                className="btn btn-sm btn-outline-primary rounded-circle"
                                style={{ width: '40px', height: '40px' }}
                                onClick={() => handlePlayTrack(track, selectedPlaylist.tracks)}
                              >
                                <i className={`bi ${
                                  player.currentTrack?.id === track.id && player.isPlaying 
                                    ? 'bi-pause-fill' 
                                    : 'bi-play-fill'
                                }`}></i>
                              </button>
                              
                              {selectedPlaylist.tracks.length > 1 && (
                                <button 
                                  className="btn btn-sm btn-outline-secondary rounded-circle"
                                  style={{ width: '40px', height: '40px' }}
                                  onClick={() => handleOpenPositionModal(track)}
                                >
                                  <i className="bi bi-arrows-move"></i>
                                </button>
                              )}
                              
                              <button 
                                className="btn btn-sm btn-outline-danger rounded-circle"
                                style={{ width: '40px', height: '40px' }}
                                onClick={() => handleRemoveTrack(selectedPlaylist.id, track.id)}
                              >
                                <i className="bi bi-trash"></i>
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          ) : (
            <div className="card shadow-sm border-0">
              <div className="card-body text-center py-5">
                <i className="bi bi-music-note-list" style={{ fontSize: '3rem', color: '#ccc' }}></i>
                <p className="mt-3 text-muted">Выберите плейлист из списка</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {showPositionModal && selectedTrackForPosition && selectedPlaylist && (
        <TrackPositionModal
          track={selectedTrackForPosition}
          totalTracks={selectedPlaylist.tracks.length}
          currentPosition={selectedPlaylist.tracks.findIndex(t => t.id === selectedTrackForPosition.id)}
          onClose={() => {
            setShowPositionModal(false);
            setSelectedTrackForPosition(null);
          }}
          onSave={handlePositionChanged}
        />
      )}
    </div>
  );
};

// frontend/angular/src/app/features/playlists/playlists-page.component.ts
import { Component, OnInit, OnDestroy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Subject, takeUntil } from 'rxjs';
import { PlaylistService } from '../../core/services/playlist.service';
import { AuthService } from '../../core/services/auth.service';
import { PlayerService } from '../../core/services/player.service';
import { NotificationService } from '../../core/services/notification.service';
import { Playlist, getPlaylistCoverUrl } from '../../core/models/playlist.model';
import { Track } from '../../core/models/track.model';
import { TrackPositionModalComponent } from './components/track-position-modal/track-position-modal.component';

@Component({
  selector: 'app-playlists-page',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    TrackPositionModalComponent
  ],
  templateUrl: './playlists-page.component.html'
})
export class PlaylistsPageComponent implements OnInit, OnDestroy {
  playlists = signal<Playlist[]>([]);
  selectedPlaylist = signal<Playlist | null>(null);
  showDeleteConfirm = signal<number | null>(null);
  showPositionModal = signal<boolean>(false);
  selectedTrackForPosition = signal<Track | null>(null);
  
  private readonly destroy$ = new Subject<void>();

  protected readonly getPlaylistCoverUrl = getPlaylistCoverUrl;

  constructor(
    private readonly playlistService: PlaylistService,
    private readonly authService: AuthService,
    private readonly playerService: PlayerService,
    private readonly notificationService: NotificationService
  ) {}

  ngOnInit(): void {
    this.loadPlaylists();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private loadPlaylists(): void {
    const user = this.authService.user();
    if (!user) return;

    this.playlistService.getUserPlaylists(user.id)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (playlists) => {
          this.playlists.set(playlists);
          if (playlists.length > 0) {
            this.selectedPlaylist.set(playlists[0]);
          }
        }
      });
  }

  selectPlaylist(playlist: Playlist): void {
    this.selectedPlaylist.set(playlist);
  }

  playTrack(track: Track, tracks: Track[]): void {
    this.playerService.playTrack(track, tracks);
  }

  removeTrack(playlistId: number, trackId: number): void {
    this.playlistService.removeTrack(playlistId, trackId)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (updatedPlaylist) => {
          this.notificationService.success('Трек удален из плейлиста');
          this.updatePlaylistInLists(updatedPlaylist);
        }
      });
  }

  openPositionModal(track: Track): void {
    this.selectedTrackForPosition.set(track);
    this.showPositionModal.set(true);
  }

  onPositionChanged(newPosition: number): void {
    const currentPlaylist = this.selectedPlaylist();
    const selectedTrack = this.selectedTrackForPosition();
    
    if (!currentPlaylist || !selectedTrack) return;

    this.playlistService.updateTrackPosition(currentPlaylist.id, selectedTrack.id, newPosition)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (updatedPlaylist) => {
          this.notificationService.success('Позиция трека изменена');
          this.updatePlaylistInLists(updatedPlaylist);
          this.showPositionModal.set(false);
          this.selectedTrackForPosition.set(null);
        },
        error: (error) => {
          this.notificationService.error('Ошибка при изменении позиции трека');
        }
      });
  }

  private updatePlaylistInLists(updatedPlaylist: Playlist): void {
    this.playlists.update(playlists =>
      playlists.map(p => p.id === updatedPlaylist.id ? updatedPlaylist : p)
    );
    if (this.selectedPlaylist()?.id === updatedPlaylist.id) {
      this.selectedPlaylist.set(updatedPlaylist);
    }
  }

  confirmDelete(playlistId: number): void {
    this.showDeleteConfirm.set(playlistId);
  }

  cancelDelete(): void {
    this.showDeleteConfirm.set(null);
  }

  deletePlaylist(playlistId: number): void {
    this.playlistService.delete(playlistId)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: () => {
          this.notificationService.success('Плейлист удален');
          this.playlists.update(playlists => playlists.filter(p => p.id !== playlistId));
          if (this.selectedPlaylist()?.id === playlistId) {
            this.selectedPlaylist.set(this.playlists()[0] || null);
          }
          this.showDeleteConfirm.set(null);
        }
      });
  }

  formatArtists(artists: { name: string }[]): string {
    return artists.map(a => a.name).join(', ');
  }

  formatDuration(seconds: number): string {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  }
}
<div class="container-fluid py-4">
  <div class="row g-4">
    <div class="col-md-4 col-lg-3">
      <div class="card shadow-sm">
        <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
          <h2 class="h5 mb-0">Мои плейлисты</h2>
          <a routerLink="/playlists/new" class="btn btn-primary btn-sm">
            <i class="bi bi-plus-lg"></i>
          </a>
        </div>
        
        <div class="list-group list-group-flush">
          @for (playlist of playlists(); track playlist.id) {
            <div class="list-group-item p-0">
              <div class="d-flex align-items-center p-3">
                <button 
                  type="button"
                  class="btn btn-link p-0 border-0 rounded me-3" 
                  style="width: 48px; height: 48px; overflow: hidden; flex-shrink: 0;"
                  (click)="selectPlaylist(playlist)">
                  <img 
                    [src]="getPlaylistCoverUrl(playlist)"
                    alt="Обложка плейлиста" 
                    style="width: 100%; height: 100%; object-fit: cover;">
                </button>
                
                <div class="flex-grow-1">
                  <div class="fw-semibold">{{ playlist.name }}</div>
                  <div class="small">
                    <span class="text-secondary">{{ playlist.tracks.length }} треков</span>
                    @if (!playlist.isPublic) {
                      <span class="badge bg-secondary ms-2">Приватный</span>
                    }
                  </div>
                </div>
                
                @if (showDeleteConfirm() === playlist.id) {
                  <div class="ms-2">
                    <button class="btn btn-sm btn-outline-success me-1" (click)="deletePlaylist(playlist.id)">
                      <i class="bi bi-check-lg"></i>
                    </button>
                    <button class="btn btn-sm btn-outline-secondary" (click)="cancelDelete()">
                      <i class="bi bi-x-lg"></i>
                    </button>
                  </div>
                } @else {
                  <button class="btn btn-sm btn-outline-danger ms-2" (click)="confirmDelete(playlist.id)">
                    <i class="bi bi-trash"></i>
                  </button>
                }
              </div>
            </div>
          } @empty {
            <div class="text-center py-4">
              <p class="text-muted mb-0">Нет плейлистов</p>
              <a routerLink="/playlists/new" class="btn btn-link">Создать первый плейлист</a>
            </div>
          }
        </div>
      </div>
    </div>

    <div class="col-md-8 col-lg-9">
      @if (selectedPlaylist(); as playlist) {
        <div class="card shadow-sm border-0">
          <div class="card-header bg-white py-3 border-bottom">
            <div class="d-flex align-items-center gap-3">
              <img 
                [src]="getPlaylistCoverUrl(playlist)"
                alt="Обложка плейлиста" 
                class="rounded shadow-sm"
                style="width: 80px; height: 80px; object-fit: cover;">
              <div class="flex-grow-1">
                <div class="d-flex align-items-center gap-2 mb-1">
                  <h1 class="h3 mb-0">{{ playlist.name }}</h1>
                  <span class="badge" [class.bg-success]="playlist.isPublic" [class.bg-secondary]="!playlist.isPublic">
                    {{ playlist.isPublic ? 'Публичный' : 'Приватный' }}
                  </span>
                </div>
                <p class="text-muted mb-0">
                  <i class="bi bi-music-note-beamed me-1"></i>
                  {{ playlist.tracks.length }} треков
                </p>
              </div>
              <div class="d-flex gap-2">
                <a [routerLink]="['/playlists', playlist.id, 'edit']" class="btn btn-outline-primary">
                  <i class="bi bi-pencil me-2"></i>
                  Редактировать
                </a>
              </div>
            </div>
          </div>

          <div class="card-body p-0">
            <div class="list-group list-group-flush">
              @for (track of playlist.tracks; track track.id; let i = $index) {
                <div class="list-group-item p-3">
                  <div class="row align-items-center g-3">
                    <div class="col-auto">
                      <span class="text-secondary fw-medium" style="width: 30px; display: inline-block;">{{ i + 1 }}</span>
                    </div>
                    
                    <div class="col">
                      <div class="d-flex flex-column">
                        <h3 class="h6 mb-1">{{ track.title }}</h3>
                        <div class="small text-secondary">
                          {{ formatArtists(track.artists) }} · {{ formatDuration(track.durationSeconds) }}
                        </div>
                      </div>
                    </div>
                    
                    <div class="col-auto">
                      <div class="d-flex gap-2">
                        <button 
                          class="btn btn-sm btn-outline-primary rounded-circle" 
                          style="width: 40px; height: 40px;"
                          (click)="playTrack(track, playlist.tracks)">
                          <i class="bi" 
                            [class.bi-play-fill]="playerService.currentTrack()?.id !== track.id || !playerService.isPlaying()"
                            [class.bi-pause-fill]="playerService.currentTrack()?.id === track.id && playerService.isPlaying()">
                          </i>
                        </button>
                        
                        @if (playlist.tracks.length > 1) {
                          <button 
                            class="btn btn-sm btn-outline-secondary rounded-circle" 
                            style="width: 40px; height: 40px;"
                            (click)="openPositionModal(track)">
                            <i class="bi bi-arrows-move"></i>
                          </button>
                        }
                        
                        <button 
                          class="btn btn-sm btn-outline-danger rounded-circle" 
                          style="width: 40px; height: 40px;"
                          (click)="removeTrack(playlist.id, track.id)">
                          <i class="bi bi-trash"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              } @empty {
                <div class="text-center py-5">
                  <i class="bi bi-music-note-beamed" style="font-size: 3rem; color: #ccc;"></i>
                  <p class="mt-3 text-muted">В плейлисте нет треков</p>
                  <a routerLink="/albums" class="btn btn-primary mt-2">
                    <i class="bi bi-plus-circle me-2"></i>
                    Добавить треки
                  </a>
                </div>
              }
            </div>
          </div>
        </div>
      } @else {
        <div class="card shadow-sm border-0">
          <div class="card-body text-center py-5">
            <i class="bi bi-music-note-list" style="font-size: 3rem; color: #ccc;"></i>
            <p class="mt-3 text-muted">Выберите плейлист из списка</p>
          </div>
        </div>
      }
    </div>
  </div>
</div>

@if (showPositionModal() && selectedTrackForPosition() && selectedPlaylist()) {
  <app-track-position-modal
    [track]="selectedTrackForPosition()!"
    [totalTracks]="selectedPlaylist()?.tracks?.length || 0"
    [currentPosition]="selectedPlaylist()?.tracks?.findIndex(t => t.id === selectedTrackForPosition()?.id) || 0"
    (closeModal)="showPositionModal.set(false)"
    (savePosition)="onPositionChanged($event)">
  </app-track-position-modal>
}
